name: cogniAI

services:
  pg:
    image: bitnami/postgresql
    ports:
      - "2508:5432"
    environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: cogniAI
    volumes:
      - pg-data:/var/lib/postgresql/pg-data
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ports:
      - "6500:6379"
    ulimits:
      memlock: -1
    volumes:
      - dragonflydata:/data
    command: ["--proactor_threads=4", "--maxmemory=1gb"]
  minio:
    image: minio/minio:latest
    ports:
      - "9005:9000" # API S3
      - "9006:9001" # Web
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
   pg-data:
   dragonflydata:
   minio-data:
